---
- hosts: all
  tasks: 
  - name: Create directory
    win_file: 
      path: C:\awx\Logs
      state: directory
      
  - name: Install Windows Updates
    win_updates:
      log_path: C:\awx\Logs\win_updates.log
      reboot: yes
      state: installed
    tags: win
